name: image_env
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.7
  - pytorch=1.3
  - torchvision=0.4.1
  - pillow=6.2.0
  - cuda100=1.0
  - numpy=1.17.2
  - pandas=0.25.1
  - scikit-image=0.15.0
  - tqdm=4.36.1
  - matplotlib=3.1.1
  - scipy=1.3.1
  - scikit-learn=0.21.3
  - seaborn=0.9.0
  - hyperopt=0.2.2
  - jupyter==1.0.0
  - black=19.*
  - ipykernel==5.1.*
  - pip=19.3.1
  - pip:
    - opencv-python